const images = {
  INPOIN_LOGO: '/static/images/logo/inpoin_logo.png',
  INPOIN_LOGO_WHITE: '/static/images/logo/inpoin_logo_white.png',
  INPOIN_LOGO_SVG: '/static/images/logo/inpoin_logo_svg.svg',
  MY_INPOIN: '/static/images/logo/logo_myinpoin.png',
  MY_INPOIN_WITH_TAGLINE: '/static/images/logo/myinpoin_with_tagline.png',
  MY_INPOIN_WITH_TELKOM: '/static/images/logo/myinpoin_with_telkom.png',
  MY_PERTAMINA: '/static/images/logo/my_pertamina.png',
  LINKAJA: '/static/images/logo/linkaja.svg',
  INDIHOME: '/static/images/logo/indihome.png',
  MY_INDIHOME: '/static/images/logo/my_indihome.png',
  TELKOMSEL_POIN: '/static/images/logo/telkomsel_poin.png',
  USEE_TV_GO: '/static/images/logo/usee_tv_go.png',
  QREN: '/static/images/logo/qren.png',
  BONUM: '/static/images/logo/bonum.png',
  APP_STORE: '/static/images/logo/app_store.svg',
  APP_STORE_DARK: '/static/images/logo/app_store_dark.svg',
  PLAY_STORE: '/static/images/logo/play_store.svg',
  PLAY_STORE_DARK: '/static/images/logo/play_store_dark.svg',
  SUCCESS_2: '/static/images/logo/success_2.png',
  VERIFY_SUCCEED: '/static/images/verify_succeed.png',
  VERIFY_FAILED: '/static/images/verify_failed.png',

  //Landing page
  HOME_HERO: '/static/images/LandingPage/home_hero.png',
  HOME_SOLUTION_1: '/static/images/LandingPage/solution_1.png',
  HOME_SOLUTION_2: '/static/images/LandingPage/solution_2.png',
  HOME_SOLUTION_3: '/static/images/LandingPage/solution_3.png',
  HOME_SOLUTION_4: '/static/images/LandingPage/solution_4.png',
  HOME_VALUES: '/static/images/LandingPage/home_values.png',
  HOME_SLIDER_1: '/static/images/LandingPage/slider_1.png',
  HOME_SLIDER_2: '/static/images/LandingPage/slider_2.png',
  HOME_SLIDER_3: '/static/images/LandingPage/slider_3.png',
  FEATURES_HERO: '/static/images/LandingPage/features_hero.png',
  FEATURES_ANALYTICAL_OVERVIEW: '/static/images/LandingPage/feature_analytical_overview.png',
  FEATURES_TARGET: '/static/images/LandingPage/features_target.png',
  FEATURES_LEVEL: '/static/images/LandingPage/features_level.png',
  FEATURES_REWARD: '/static/images/LandingPage/features_reward.png',
  MY_INPOIN_HERO: '/static/images/LandingPage/my_inpoin_hero.png',
  MY_INPOIN_APP: '/static/images/LandingPage/my_inpoin_app.png',
  MY_INPOIN_WALLET: '/static/images/LandingPage/my_inpoin_wallet.png',
  MY_INPOIN_EXCHANGE: '/static/images/LandingPage/my_inpoin_exchange.png',
  MY_INPOIN_REDEEM: '/static/images/LandingPage/my_inpoin_redeem.png',

  IDENTIFY_BUSINESS: '/static/images/identify_business.png',

  INDUSTRY_TELECOM: '/assets/images/Visual--Based-On-Industries-Telecom.png',
  INDUSTRY_HEALTH: '/assets/images/Visual--Based-On-Industries-Health.png',
};

export default images;